### ISSUE TITLE
Plugin not working correctly

### ISSUE THREAD

**Issue by AnthonMS** [Garulf/Search-MDI#7]
Hey, just thought I would try out this plugin, since you said they had fixed all the issues regarding python plugins for flow launcher.

I have installed the newest release of Flow Launcher v1.8.2. I have installed the dependencies and python and all that. Because it works, but only some times.
When I go to the start menu and Exit flow launcher and then I start Flow again, the Launcher that pops up automatically, that is where the plugin works as expected, but when I close that and se the alt + space shortcut to open flow again, it doesn't work.

I don't think this has anything to do with your plugin, rather my setup or the released flow launcher version I have installed. But thought you should know.

EDIT: Actually just tested around with it some more, and I have found something weird.
When I open the launcher with alt + space, the plugin doesn't work. But when I open it with Win + r and delete the ">", then it works as expected.. Very weird, I don't know why this is, but maybe talk with the Flow Launcher devs. They are very helpfull if you create an issue on their repo.

**Comment by AnthonMS** [comment]
I'm just an idiot.

For other people as dumb as me (I'm sorry for you, because I'm quite dumb apparently). The solution that worked for me was, use the correct launcher.
PowerToys have the same shortcut as flow Alt + Space. Go into PowerToys settings, POwerToys Run Tab and change the shortcut to something other than Alt + Space. (I changed it to Ctrl + Space). Or you can disable PowerToys Run completely.

**Comment by Garulf** [comment]
> I'm just an idiot.
> 
> For other people as dumb as me (I'm sorry for you, because I'm quite dumb apparently). The solution that worked for me was, use the correct launcher.
> PowerToys have the same shortcut as flow Alt + Space. Go into PowerToys settings, POwerToys Run Tab and change the shortcut to something other than Alt + Space. (I changed it to Ctrl + Space). Or you can disable PowerToys Run completely.

No worries, hopefully with https://github.com/Flow-Launcher/Flow.Launcher/discussions/652 PowrToys will no longer be needed.

**Comment by AnthonMS** [comment]
> No worries, hopefully with [Flow-Launcher/Flow.Launcher#652](https://github.com/Flow-Launcher/Flow.Launcher/discussions/652) PowrToys will no longer be needed.

Oh that looks promising. I have given it an upvote for the devs to know there are more people wanting this feature implemented.
